// ============================================================================
// VentureFlow: Just for Kids — JOKE BANK
// ----------------------------------------------------------------------------
// A big, deterministic pile of clean jokes for the under-8 crowd: knock-knocks,
// riddles, and one-liners. "Deterministic" is doing real work in that sentence
// — this file contains zero randomness (no Math.random, no Date.now, nothing
// that could make two imports disagree with each other). Every joke below is
// a literal string, hand-picked or hand-paired for actual comedic sense — we
// do NOT cross-multiply word banks blindly, because "Why did the giraffe eat
// a sandwich? Because it was two tired!" is nonsense, not a joke. Where you
// see a bank of [setup, punchline] tuples mapped into objects below, every
// tuple was composed as a pair on purpose; the .map() calls only exist to
// avoid re-typing `{ id, type, ... }` boilerplate a few hundred times, not to
// generate content at runtime.
//
// Organization: three literal banks (knock-knocks, riddles, one-liners),
// each grouped into small themed batches (food, animals, space, dinosaurs,
// pirates, robots, school, weather, family, classic names, etc.) so the
// humor stays varied instead of turning into 400 versions of the same gag.
// IDs are assigned by array position within each bank, so don't reorder
// existing entries — append new ones instead if this file grows further.
//
// Content bar: every single joke here needs to land for a kid who is, say,
// six. That means simple words, silly-not-scary, zero innuendo, nothing
// mean about how anyone looks, and no borrowed characters from movies, TV,
// or games — just plain public-domain-style wordplay about animals, food,
// space, dinosaurs, pirates, robots, weather, school, and family.
// ============================================================================

// ---------------------------------------------------------------------------
// KNOCK-KNOCK JOKES — [name, punchline] tuples.
// The UI supplies the "Knock knock! / Who's there? / {name}. / {name} who?"
// wrapper; the tuple only needs to supply a name and a punchline that reads
// naturally as the answer to "{name} who?".
// ---------------------------------------------------------------------------
const KNOCK_KNOCK_BANK = [
  // --- Classic favorites -----------------------------------------------
  ['Lettuce', "Lettuce in, it's cold out here!"],
  ['Boo', "Don't cry, it's just a joke!"],
  ['Little Old Lady', "I didn't know you could yodel!"],
  ['Dwayne', 'Dwayne the bathtub, I\'m drowning!'],
  ['Interrupting Cow', 'MOO!'],
  ['Anita', 'Anita borrow a pencil, please!'],
  ['Doris', "Doris locked, that's why I'm knocking!"],
  ['Wendy', 'Wendy you gonna let me in?'],
  ['Howard', 'Howard you like a hug right now?'],
  ['Amos', 'Amos-quito just bit me, ouch!'],
  ['Alaska', 'Alaska one more time, will you let me in?'],
  ['Ida', 'Ida know, I forgot my own joke!'],
  ['Iva', 'Iva sore hand from knocking so much!'],
  ['Ivan', 'Ivan idea, let\'s go get ice cream!'],
  ['Justin', 'Justin time for dinner, I hope!'],
  ['Juan', 'Juan more chance to guess who it is!'],
  ['Watson', 'Watson your mind today? Tell me!'],
  ['Wanda', 'Wanda around the block and got lost!'],
  ['Warren', 'Warren you paying attention to me?'],
  ['Norway', "Norway am I leaving until you open up!"],
  ['Olive', 'Olive you and I miss you already!'],
  ['Cash', "Cash me if you can, I'm running late!"],
  ['Canoe', 'Canoe come out and play with me?'],
  ['Dishes', "Dishes a very silly joke, but let me in anyway!"],
  ['Dozen', 'Dozen anyone want to let me in?'],
  ['Eiffel', 'Eiffel so happy to see you today!'],
  ['Europe', "Europe early, I wasn't expecting you yet!"],
  ['Felix', 'Felix-cited to see your face!'],
  ['Gladys', "Gladys isn't it a great day outside?"],
  ['Harry', "Harry up, we're going to be late!"],
  ['Hal', "Hal-o there, how's it going?"],
  ['Iowa', 'Iowa you a favor, thanks for opening up!'],
  ['Irish', 'Irish you a happy birthday!'],
  ['Isabel', "Isabel broken? I had to knock instead!"],
  ['Keith', "Keith your voice down, the baby's asleep!"],
  ['Ken', 'Ken you please let me in already?'],
  ['Luke', "Luke through the window and you'll see it's me!"],
  ['Max', 'Max no difference, just let me in!'],
  ['Noah', 'Noah good place we could grab lunch?'],
  ['Oswald', 'Oswald my gum, do you have a mint?'],
  ['Otto', 'Otto know better than to forget my key!'],
  ['Pecan', 'Pecan someone your own size!'],
  ['Ralph', "Ralph like a puppy if you don't let me in!"],
  ['Sam', 'Sam-thing smells delicious in there!'],
  ['Sarah', 'Sarah doctor in the house? I have a splinter!'],
  ['Stan', "Stan back, I'm coming in!"],
  ['Sue', 'Sue-per excited to see you today!'],
  ['Tank', 'Tank you very much for letting me in!'],
  ['Thermos', 'Thermos be a better way to say hello!'],
  ['Tuba', 'Tuba toothpaste, please, mine is empty!'],
  ['Val', 'Val-entine, will you be mine?'],
  ['Vera', 'Vera-y happy to finally see you!'],
  ['Vincent', 'Vincent doors are locked, I had to knock!'],
  ['Wooden', 'Wooden you like to know?'],
  ['Yukon', 'Yukon count on me to knock loudly!'],
  ['Zoo', 'Zoo you want to go see the animals today?'],
  ['Annie', "Annie one home? I've been knocking forever!"],
  ['Arthur', 'Arthur any cookies left for me?'],
  ['Ash', "Ash should have brought my umbrella, it's raining!"],
  ['Beets', "Beets me why you haven't opened the door yet!"],
  ['Ben', 'Ben knocking for five minutes, let me in!'],
  ['Dewey', 'Dewey have to stand out here all day?'],
  ['Etch', 'Etch-a-sketch is my favorite toy!'],
  ['Freeze', 'Freeze a jolly good fellow, that\'s what I am!'],
  ['Handel', "Handel with care, I'm fragile!"],
  ['Harmony', 'Harmony times do I have to knock?'],
  ['Hatch', 'Hatch you doing this fine day?'],
  ['Honda', 'Honda count of three, open this door!'],
  ['Hugo', 'Hugo to school before eight, right?'],
  ['Icing', 'Icing a beautiful song, want to hear it?'],
  ['Iguana', 'Iguana be your friend, open up!'],
  ['Emma', 'Emma-zed at how long you take to answer the door!'],
  ['Fiona', 'Fiona way to open this door, please do!'],
  ['Gary', 'Gary on with your day, I was just visiting!'],
  ['Hannah', 'Hannah out with me today?'],
  ['Ian', "Ian-jured my finger from knocking so much!"],
  ['Jenny', "Jenny-us idea, let's go get ice cream!"],
  ['Kyle', "Kyle-ing time until you open this door!"],
  ['Lena', "Lena little closer, I have a secret!"],
  ['Mandy', "Mandy the fort, I'm coming in!"],
  ['Nora', "Nora good reason why you haven't opened yet!"],
  ['Ollie', 'Ollie the way from home just to see you!'],
  ['Penny', 'Penny for your thoughts, open up!'],
  ['Quinn', 'Quinn-cidence that we both love knock-knock jokes!'],
  ['Rita', "Rita book with me, it's story time!"],
  ['Sammy', 'Sammy up already, let\'s go play!'],
  ['Tara', 'Tara-ific to see you, open up!'],
  ['Uma', "Uma-zing, you finally opened the door!"],
  ['Vicky', 'Vicky-tory is mine, I win the knocking contest!'],
  ['Wyatt', 'Wyatt take you so long to open the door?'],
  ['Xander', "Xander-stand why you're not answering?"],
  ['Yara', 'Yara-ally going to make me wait out here?'],
  ['Zack', "Zack-tly on time, aren't I?"],
  ['Adder', 'Adder you doing today?'],
  ['Etiquette', 'Etiquette is knocking politely, so here I am!'],
  ['Denise', 'Denise are itchy, do you have any lotion?'],
  ['Nobel', "Nobel, so I knocked instead!"],

  // --- Food & drink -------------------------------------------------------
  ['Orange', "Orange you glad I didn't say banana?"],
  ['Honeydew', 'Honeydew you want to hear another joke?'],
  ['Butter', 'Butter late than never!'],
  ['Waffle', 'Waffle we do without you? Come on in!'],
  ['Pizza', 'Pizza cake would be great right now!'],
  ['Donut', "Donut ask me, I'm just as confused as you!"],
  ['Cereal', 'Cereal pleasure to meet you!'],
  ['Muffin', "Muffin much is happening, just wanted to say hi!"],
  ['Omelette', "Omelette you in, it's chilly!"],
  ['Turnip', 'Turnip the music, this is my favorite song!'],
  ['Cantaloupe', 'Cantaloupe with you, my parents said no!'],
  ['Watermelon', 'Watermelon we having for lunch today?'],
  ['Celery', 'Celery-bration time, let\'s have a party!'],
  ['Radish', 'Radish to go, are you ready?'],
  ['Pickle', 'Pickle you up at three o\'clock!'],
  ['Broccoli', "Broccoli doesn't like me, but I like broccoli!"],
  ['Potato', "Potato-ly forgot my key, can I come in?"],
  ['Tomato', 'Tomato-rrow is another day, see you then!'],
  ['Peas', 'Peas open the door, my hands are full!'],
  ['Bacon', 'Bacon a cake for your birthday!'],
  ['Honey', "Honey, I'm home!"],
  ['Sugar', 'Sugar you gonna let me in or what?'],
  ['Soda', 'Soda you want to play a game with me?'],
  ['Taco', "Taco 'bout a long day, let me in!"],
  ['Nacho', 'Nacho average knock-knock joke!'],
  ['Sundae', "Sundae's the only day I get to sleep in!"],
  ['Jelly', 'Jelly beans are my favorite candy!'],
  ['Grape', 'Grape to see you, open up!'],
  ['Cookie', "Cookie doesn't lock, so I let myself in!"],
  ['Apple', 'Apple-y birthday to you!'],
  ['Plum', "Plum-ber's here to fix your leaky sink!"],
  ['Mushroom', 'Mushroom for one more friend at the table?'],
  ['Pretzel', "Pretzel be a good time, I promise!"],
  ['Marshmallow', 'Marshmallow you a story about my day!'],
  ['Cupcake', "Cupcake to my house, we're having a party!"],
  ['Ketchup', 'Ketchup with me, I have so much to tell you!'],
  ['Mustard', 'Mustard up the courage to knock on your door!'],
  ['Noodle', 'Noodle around, I forgot why I knocked!'],
  ['Popcorn', 'Popcorn is ready, come watch a movie!'],
  ['Pancake', "Pancake we talk? It's important!"],
  ['Berry', 'Berry nice to meet you!'],
  ['Fig', 'Fig-ure it out, I forgot my key again!'],
  ['Kiwi', "Kiwi come in? It's freezing!"],
  ['Lemon', 'Lemon-ade is the best drink on a hot day!'],
  ['Peach', 'Peach you later, gotta run!'],
  ['Melon', 'Melon-choly music makes me sleepy!'],
  ['Coconut', "Coconut believe you didn't hear me knock!"],
  ['Raisin', "Raisin the roof, let's celebrate!"],
  ['Spinach', "Spinach my way in if you don't open up!"],
  ['Carrot', 'Carrot all about you, open the door!'],
  ['Beetroot', 'Beet it! I mean, let me in!'],
  ['Yam', 'Yam glad to see you today!'],
  ['Squash', "Squash the bugs, they're everywhere!"],
  ['Cheese', 'Cheese a lovely person, let her in!'],
  ['Ham', 'Ham-azing to see you, open up!'],
  ['Egg', "Egg-cited to see you, let me in!"],
  ['Toast', 'Toast to a great day, cheers!'],
  ['Syrup', "Syrup and shine, it's morning!"],

  // --- Animals --------------------------------------------------------
  ['Owl', "Owl be there in a minute!"],
  ['Gorilla', "Gorilla me a hamburger, I'm starving!"],
  ['Toucan', 'Toucan play this game, can I join?'],
  ['Koala', 'Koala-ty time together is all I want!'],
  ['Otter', 'Otter come out and play with me!'],
  ['Hare', 'Hare today, gone tomorrow!'],
  ['Moose', "Moose be my lucky day, you're home!"],
  ['Whale', 'Whale, whale, whale, look who it is!'],
  ['Cow', 'Cow-culate how long it took me to knock!'],
  ['Deer', 'Deer me, I forgot my umbrella!'],
  ['Bear', "Bear with me, I'm running late!"],
  ['Sheep', 'Sheep happens, I lost my key again!'],
  ['Goat', 'Goat to be kidding, open the door!'],
  ['Mouse', 'Mouse-tache you a question, may I come in?'],
  ['Hamster', 'Hamster up the stairs, wait for me!'],
  ['Panda', "Panda-monium if you don't let me in soon!"],
  ['Turtle', 'Turtle-y forgot my key at home!'],
  ['Frog', 'Frog-ot my umbrella, can I borrow yours?'],
  ['Cricket', "Cricket's chirping, let's go outside!"],
  ['Beaver', 'Beaver-y happy to see you today!'],
  ['Skunk', "Skunk you smell that? Someone's cooking!"],
  ['Zebra', "Zebra-vo, you finally opened the door!"],
  ['Giraffe', "Giraffe-fully glad you're home!"],
  ['Elephant', 'Elephant-astic to see your friendly face!'],
  ['Kangaroo', "Kangaroo you believe it's finally the weekend?"],
  ['Penguin', 'Penguin-ly happy you answered the door!'],
  ['Seal', "Seal the deal, let's be best friends!"],
  ['Dolphin', "Dolphin-itely glad to see you!"],
  ['Octopus', 'Octo-puss loves to play hide and seek!'],
  ['Bee', 'Bee careful, the door might be sticky!'],
  ['Ant', 'Ant-y ready to go outside and play?'],
  ['Spider', 'Spider-web is stuck all over my shoe!'],
  ['Ladybug', "Ladybug on your sleeve, don't move!"],
  ['Snail', "Snail-ing it here as fast as I can!"],
  ['Fox', "Fox-cited to see you, open up!"],
  ['Wolf', "Wolf you please let me in, it's cold!"],
  ['Rooster', "Rooster you awake yet? It's morning!"],
  ['Duck', 'Duck, duck, goose, now let me in!'],
  ['Goose', "Goose who's knocking on your door!"],
  ['Swan', "Swan more minute and I'll be inside!"],
  ['Camel', "Camel down, I'm just here to visit!"],
  ['Llama', 'Llama tell you a joke, ready?'],
  ['Alpaca', "Alpaca my bags, we're going on a trip!"],
  ['Rhino', "Rhino-body is home except you!"],
  ['Hippo', 'Hippo-tamus is my favorite zoo animal!'],
  ['Cheetah', "Cheetah never wins, so let's play fair!"],
  ['Leopard', 'Leopard-y for a hundred, please open up!'],
  ['Tiger', "Tiger shoes on, we're going for a walk!"],
  ['Lion', "Lion around all day, let's do something fun!"],
  ['Monkey', 'Monkey around and you\'ll find out!'],
  ['Squirrel', 'Squirrel-y around the yard, catch me if you can!'],
  ['Raccoon', "Raccoon-t on it, I'll be right on time!"],
  ['Bat', "Bat you didn't expect to see me tonight!"],
  ['Crow', 'Crow-d of friends is waiting outside!'],
  ['Parrot', "Parrot-y time, let's celebrate!"],
  ['Flamingo', "Flamingo-ing to be late if you don't hurry!"],
  ['Peacock', "Peacock-a-doodle-doo, wake up sleepyhead!"],
  ['Snake', "Snake a look outside, it's snowing!"],
  ['Lizard', 'Lizard the button and let me in!'],

  // --- Weather & nature -------------------------------------------------
  ['Snow', 'Snow use, I forgot my umbrella!'],
  ['Rain', 'Rain-y days are my favorite for reading!'],
  ['Sunny', "Sunny side up, that's how I like my eggs!"],
  ['Icy', 'Icy you shivering, let me in quick!'],
  ['Windy', 'Windy you finally going to answer the door?'],
  ['Storm', 'Storm the castle! I mean, let me in!'],
  ['Frost', 'Frost things first, open the door!'],
  ['Thunder', "Thunder you doing standing out here?"],
  ['Cloud', 'Cloud you please open the door already?'],
  ['Breeze', "Breeze-y outside, can I come warm up?"],
  ['Dew', 'Dew you know what time it is?'],
  ['Mist', "Mist you so much, glad you're home!"],
  ['Hail', 'Hail yes, I made it just in time!'],
  ['Rainbow', "Rainbow-t of colors, isn't it pretty outside?"],
  ['Puddle', "Puddle my feet in, it's flooding out here!"],
  ['Sunshine', "Sunshine you're glad to see me!"],
  ['Autumn', 'Autumn leaves are falling, come look!'],
  ['Blizzard', 'Blizzard out here, let me in quick!'],
  ['Drizzle', "Drizzle be the day we finally hang out!"],
  ['Twister', 'Twister game, want to play after this?'],
  ['Tree', 'Tree-t or treat, got any snacks?'],
  ['Leaf', "Leaf me alone! Just kidding, let me in!"],
  ['Flower', 'Flower power, open the door already!'],
  ['Garden', "Garden the gate, I'm coming through!"],
  ['Acorn', 'Acorn-y joke, but let me in anyway!'],
  ['Pinecone', 'Pinecone-ly wanted to say hello!'],
  ['Daisy', 'Daisy after day, I keep forgetting my key!'],
  ['Petal', "Petal to the metal, let's go!"],
  ['Branch', 'Branch out and make a new friend, me!'],

  // --- Numbers ----------------------------------------------------------
  ['Two', 'Two whom it may concern, open up!'],
  ['Four', 'Four-got my key again, oops!'],
  ['Eight', "Eight my whole lunch, I'm so full!"],
  ['Nine', 'Nine-ty nine problems, and my key is one!'],
  ['Seven', 'Seven-teen minutes late, sorry about that!'],
  ['Ten', 'Ten-derly knocking, please let me in!'],
  ['Six', 'Six of one, half a dozen of the other, just open up!'],
  ['Eleven', 'Eleven-ses time, do you have any snacks?'],
  ['Zero', "Zero in on the fact that I'm locked out!"],
  ['One', 'One more chance to guess who it is!'],
  ['Forty', 'Forty winks and I overslept, sorry I\'m late!'],

  // --- Space --------------------------------------------------------------
  ['Comet', 'Comet closer, I have a secret to tell you!'],
  ['Saturn', 'Saturn my way over as fast as I could!'],
  ['Neptune', "Neptune-ly the best planet, don't you think?"],
  ['Venus', 'Venus the next bus coming, do you know?'],
  ['Meteor', 'Meteor me at the park later?'],
  ['Pluto', "Pluto's still a planet in my heart!"],
  ['Mars', "Mars-hmallow, want to make s'mores?"],
  ['Rocket', "Rocket 'n roll, let's blast off!"],
  ['Astro', 'Astro-nomically happy to see you today!'],
  ['Orbit', 'Orbit chilly out here, can I come in?'],
  ['Galaxy', "Galaxy you didn't hear me the first time!"],
  ['Star', "Star-ting to get cold out here!"],
  ['Moon', 'Moon-day already? Where did the weekend go?'],
  ['Nova', "Nova mind, I'll just let myself in!"],
  ['Cosmo', "Cosmo on, we're going to be late!"],
  ['Alien', 'Alien you a hand with those groceries!'],
  ['Eclipse', 'Eclipse my mind what I even came here for!'],

  // --- School -------------------------------------------------------------
  ['Pencil', 'Pencil you in for a playdate tomorrow!'],
  ['Chalk', 'Chalk full of jokes today, want to hear more?'],
  ['Ruler', 'Ruler the school, that\'s my dream job!'],
  ['Eraser', 'Eraser this mess before the teacher sees!'],
  ['Recess', 'Recess is my favorite part of the day!'],
  ['Backpack', "Backpack your bags, we're going on a trip!"],
  ['Homework', 'Homework-ed hard, can I take a break now?'],
  ['Crayon', "Crayon believe how long I've been knocking?"],
  ['Glue', 'Glue-nited we stand, divided we fall!'],
  ['Scissors', 'Scissors a good day for a haircut!'],
  ['Marker', "Marker my words, I'll be back tomorrow!"],
  ['Locker', "Locker up, don't forget your homework!"],
  ['Principal', 'Principal-ly I just wanted to say hi!'],
  ['Bus', "Bus-y day today, mind if I come in?"],
  ['Alphabet', "Alphabet you didn't expect to see me here!"],

  // --- Family --------------------------------------------------------------
  ['Grandpa', "Grandpa-rents are the best, aren't they?"],
  ['Auntie', 'Auntie up for a game of cards?'],
  ['Uncle', "Uncle-ss you open this door, I'll keep knocking!"],
  ['Cousin', 'Cousin around the neighborhood, thought I\'d stop by!'],
  ['Sister', 'Sister-ly love, now let me in!'],
  ['Brother', 'Brother believe it, I forgot my key again!'],
  ['Papa', 'Papa-razzi is here, smile for the camera!'],
  ['Baby', "Baby it's cold outside, let me in!"],
  ['Twin', 'Twin-kle twinkle little star, open this door!'],
  ['Nana', "Nana your business, just open the door!"],

  // --- Dinosaurs ------------------------------------------------------------
  ['Rex', 'Rex-cited to see you, open up!'],
  ['Stego', "Stego right past you if you don't move!"],
  ['Raptor', 'Raptor present for you, happy birthday!'],
  ['Dino', 'Dino-mite to see you today!'],
  ['Bronto', "Bronto-saurus, that's a mouthful, just let me in!"],
  ['Fossil', 'Fossil-y hope you remember me!'],
  ['Ptera', 'Ptera-dactyl flew right by, did you see it?'],
  ['Tricera', 'Tricera-tops my list of favorite dinosaurs!'],

  // --- Pirates -----------------------------------------------------------
  ['Matey', 'Matey I come aboard, please?'],
  ['Arr', 'Arr you gonna let me in or what?'],
  ['Anchor', "Anchor's aweigh, let's set sail!"],
  ['Treasure', "Treasure the moment, I'm finally here!"],
  ['Plank', 'Plank you very much for opening the door!'],
  ['Compass', 'Compass-sionate people always let pirates in!'],
  ['Cutlass', 'Cutlass short, I really need to use your bathroom!'],
  ['Doubloon', 'Doubloon my shoelace, can you help me tie it?'],

  // --- Robots ---------------------------------------------------------------
  ['Robo', "Robo-t sure took you long enough to answer!"],
  ['Circuit', 'Circuit out, I think my legs are tired!'],
  ['Gizmo', 'Gizmo way inside so we can build something!'],
  ['Beep', "Beep-utiful day to visit, isn't it?"],
  ['Byte', 'Byte-sized snack, do you have any?'],
  ['Wire', 'Wire you not answering the door faster?'],
  ['Bolt', 'Bolt the door after I come in, please!'],
  ['Laser', 'Laser focused on getting inside, let me in!'],

  // --- Colors ---------------------------------------------------------------
  ['Violet', "Violet's my favorite color, what's yours?"],
  ['Amber', 'Amber-y glad to finally see you!'],
  ['Scarlet', 'Scarlet all over the place, I spilled paint!'],
  ['Indigo', 'Indigo outside and play, come on!'],
  ['Coral', "Coral you believe how long I've been standing here?"],
  ['Ivory', 'Ivory much wanted to see you today!'],
  ['Rose', 'Rose are red, violets are blue, let me in, boo!'],

  // --- Sports & hobbies -------------------------------------------------
  ['Soccer', 'Soccer to me, I forgot the score!'],
  ['Baseball', "Baseball me later, I'm busy right now!"],
  ['Basketball', 'Basketball-oons are so much fun to bounce!'],
  ['Tennis', "Tennis my favorite number, that's why I knocked ten times!"],
  ['Hockey', "Hockey pokey, that's what it's all about!"],
  ['Golf', 'Golf you a present, come see!'],
  ['Swim', "Swim-ply couldn't wait to see you!"],
  ['Biking', "Biking all the way here, I'm tired!"],
  ['Skate', 'Skate-ing outside, want to join me?'],
  ['Bowling', 'Bowling over with excitement to see you!'],

  // --- Music --------------------------------------------------------------
  ['Piano', 'Piano-ly have a minute? Can we talk?'],
  ['Drum', 'Drum-roll please, I have exciting news!'],
  ['Harp', 'Harp-y to see you, open up!'],
  ['Cello', "Cello there, how's it going?"],
  ['Trumpet', "Trumpet up, we're going to be late!"],
  ['Violin', 'Violin-ly wanted to say hello!'],
  ['Banjo', "Banjo know how long I've been out here?"],
  ['Guitar', 'Guitar ready to jam with me?'],

  // --- Ocean --------------------------------------------------------------
  ['Shrimp', "Shrimp-ly the best day ever, isn't it?"],
  ['Crab', "Crab-by if I don't get a snack soon!"],
  ['Clam', "Clam down, I'm just here to say hi!"],
  ['Shell', 'Shell we go to the beach today?'],
  ['Reef', 'Reef-reshing to see a friendly face!'],
  ['Jellyfish', 'Jellyfish and chips sound great for dinner!'],
  ['Starfish', "Starfish-ing for compliments, but really I just missed you!"],
  ['Kelp', 'Kelp me carry these groceries, please!'],
  ['Wave', "Wave hello, I've been standing here forever!"],

  // --- Insects --------------------------------------------------------------
  ['Beetle', 'Beetle you to the park, race you there!'],
  ['Moth', 'Moth-er told me to come say hi!'],
  ['Firefly', "Firefly-ing by to see how you're doing!"],
  ['Dragonfly', 'Dragonfly-ing high, want to come outside?'],
  ['Caterpillar', 'Caterpillar-y patient waiting for you to open up!'],

  // --- Vehicles --------------------------------------------------------------
  ['Taxi', 'Taxi-ted to see you, open the door!'],
  ['Train', "Train-ing hard for the big race, wanna help?"],
  ['Plane', 'Plane and simple, I forgot my key!'],
  ['Boat', 'Boat-h of us should hang out today!'],
  ['Truck', 'Truck or treat, got any candy?'],
  ['Scooter', 'Scooter on over here and open the door!'],
  ['Wagon', 'Wagon my finger at you for taking so long!'],

  // --- Toys -------------------------------------------------------------------
  ['Balloon', 'Balloon-g time no see, open up!'],
  ['Kite', "Kite time we hung out, don't you think?"],
  ['Puzzle', "Puzzle-d why you haven't opened the door yet!"],
  ['Yoyo', "Yoyo, it's me, open up already!"],
  ['Blocks', 'Blocks party at my house, want to come?'],
  ['Teddy', 'Teddy or not, here I come!'],

  // --- Feelings & misc -----------------------------------------------------
  ["Happy", "Happy to see you, that's why I'm smiling!"],
  ['Silly', 'Silly me, I forgot why I even knocked!'],
  ['Giggle', 'Giggle-y excited to hang out with you today!'],
  ['Bubble', "Bubble trouble if you don't let me in soon!"],

  // --- Jobs -----------------------------------------------------------------
  ['Doctor', "Doctor's orders, let me in for a checkup!"],
  ['Teacher', 'Teacher me something new today!'],
  ['Chef', "Chef's special today is a big hug, open up!"],
  ['Farmer', 'Farmer-ly speaking, I really need to use your bathroom!'],
  ['Firefighter', "Firefighter-ly speaking, is it hot in there or just me?"],
  ['Baker', "Baker's dozen of cookies, want to share?"],

  // --- Holidays & seasons -------------------------------------------------
  ['Party', "Party time, let's celebrate!"],
  ['Winter', "Winter you going to let me in? It's freezing!"],
  ['Summer', 'Summer day this would be perfect for swimming!'],
  ['Spring', 'Spring into action and open this door!'],
  ['Present', 'Present and accounted for, open up!'],
  ['Candle', "Candle you believe it's already my birthday?"],

  // --- Geography ------------------------------------------------------------
  ['Utah', 'Utah-ly forgot my umbrella, can I come in?'],
  ['Cuba', "Cuba believe how long I've been knocking?"],
  ['China', "China up your room, it's a mess!"],
  ['Kenya', 'Kenya guess who it is?'],
  ['Chile', "Chile out here, let me in!"],
  ['Turkey', 'Turkey trot, that\'s my new dance move!'],
];

// ---------------------------------------------------------------------------
// RIDDLES — [question, answer] tuples.
// ---------------------------------------------------------------------------
const RIDDLE_BANK = [
  // --- Classic "what has..." riddles --------------------------------------
  ["What has hands but can't clap?", 'A clock!'],
  ['What has a face but no eyes, and two hands but no arms?', 'A clock!'],
  ["What has legs but can't walk?", 'A table!'],
  ['What has a neck but no head?', 'A bottle!'],
  ["What has teeth but can't bite?", 'A comb!'],
  ["What has ears but can't hear?", 'A cornfield!'],
  ['What has a bed but never sleeps?', 'A river!'],
  ['What has keys but no locks?', 'A piano!'],
  ['What has a thumb but no fingers?', 'A mitten!'],
  ["What has wings but can't fly?", 'A penguin!'],
  ["What has a tongue but can't talk?", 'A shoe!'],
  ["What has an eye but can't see?", 'A needle!'],
  ['What has a spine but no bones?', 'A book!'],
  ['What has branches but no leaves or fruit?', 'A bank!'],
  ['What has a ring but no finger?', 'A telephone!'],
  ['What has a head and a tail but no body?', 'A coin!'],
  ['What has holes but can still hold water?', 'A sponge!'],
  ['What has a bark but no bite?', 'A tree!'],
  ['What has four wheels and flies?', 'A garbage truck!'],
  ['What has cities but no houses, forests but no trees, and rivers but no water?', 'A map!'],
  ['What can you catch but never throw?', 'A cold!'],
  ['What can you break without ever touching it?', 'A promise!'],
  ['What goes up but never comes back down?', 'Your age!'],
  ['What gets wetter the more it dries?', 'A towel!'],
  ['What has to be broken before you can use it?', 'An egg!'],
  ['What runs but never walks?', 'Water!'],
  ['What can travel all around the world while staying in one spot?', 'A stamp!'],
  ["What has many teeth but can't eat a thing?", 'A zipper!'],
  ['What kind of coat can only be put on when it is wet?', 'A coat of paint!'],
  ['What goes through cities and fields but never actually moves?', 'A road!'],
  ['What invention lets you look right through a wall?', 'A window!'],
  ['What building in your town has the most stories?', 'The library!'],
  ["What has a bottom at the very top?", 'Your legs!'],
  ['What has three feet but cannot walk a single step?', 'A yardstick!'],
  ['What always sleeps with its shoes on?', 'A horse!'],
  ['What can fill up a whole room but takes up no space?', 'Light!'],
  ['What goes up when the rain comes down?', 'An umbrella!'],
  ['What has many rings but no fingers?', 'A tree trunk!'],
  ['What five-letter word becomes shorter when you add two letters to it?', 'Short!'],
  ['What gets bigger the more you take away from it?', 'A hole!'],
  ['What can you hold in your left hand but never in your right hand?', 'Your right hand!'],
  ['What has a heart that does not beat?', 'An artichoke!'],
  ['What kind of room has no doors or windows?', 'A mushroom!'],
  ['What can you never eat for breakfast?', 'Lunch and dinner!'],
  ['What is full of holes but still holds water?', 'A sponge!'],

  // --- Animal riddles -------------------------------------------------------
  ['What do you call a dinosaur that crashes his car?', 'Tyrannosaurus wrecks!'],
  ['What do you call a dinosaur that never gives up?', 'A try-try-triceratops!'],
  ['What do you call a dinosaur with a huge vocabulary?', 'A thesaurus!'],
  ['What do you call a sleeping dinosaur?', 'A dino-snore!'],
  ['What do you call a bear caught out in the rain?', 'A drizzly bear!'],
  ['What do you call a bear with no ears?', 'A B!'],
  ['What do you call a cow during an earthquake?', 'A milkshake!'],
  ['What do you call a cow that plays music?', 'A moo-sician!'],
  ['What do you call a cow that never gives milk?', 'An udder failure!'],
  ['What do you call a dog that can do magic tricks?', 'A labracadabrador!'],
  ['What do you call a dog that tells the time?', 'A watch dog!'],
  ['What do you call an owl who can do magic tricks?', 'Hoo-dini!'],
  ['What do you call a snake that works on a building site?', 'A boa constructor!'],
  ['What do you call a snake that is exactly 3.14 meters long?', 'A pi-thon!'],
  ['What do you call a fish with no eye?', 'A fsh!'],
  ['What do you call a fish wearing a bow tie?', 'So-fish-ticated!'],
  ['What do you call a bear with no teeth?', 'A gummy bear!'],
  ['What do you call an elephant that never matters?', 'An irrelephant!'],
  ['What do you call an elephant that can fly?', 'A jumbo jet!'],
  ['What do you call a pony with a cough?', 'A little hoarse!'],
  ['What do you call a frog that is illegally parked?', 'Toad away!'],
  ['What do you call an alligator wearing a vest?', 'An investigator!'],
  ['What do you call a cat that loves to bowl?', 'An alley cat!'],
  ['What do you call a cat that loves ice cream?', 'A sundae cat!'],
  ['What do you call a bird that is always gloomy?', 'A blue jay!'],
  ['What do you call a very rude bird?', 'A mockingbird!'],
  ['What do you call a fish that needs help with money?', 'A loan shark!'],
  ['What do you call a sheep with no legs?', 'A cloud, from far away!'],
  ['What do you call a sleepy dinosaur that everyone avoids?', 'A dino-snore, obviously!'],
  ['What do you call a group of eight octopuses?', 'An octo-bunch!'],
  ['What do you call an ant who fights crime?', 'A vigil-ant-e!'],
  ['What do you call a pig that knows karate?', 'A pork chop!'],
  ['What do you call a rabbit that tells good jokes?', 'A funny bunny!'],
  ['What do you call a spider with no legs?', 'A raisin!'],
  ['What do you call a dog magician who disappears in a puff of smoke?', 'A labracadabrador!'],
  ['What do you call a bee that just cannot make up its mind?', 'A maybe!'],
  ['What do you call a very lazy kangaroo?', 'A pouch potato!'],
  ['What do you call a boastful, opinionated mule?', 'A know-it-all-donkey!'],
  ['What do you call two birds in love?', 'Tweethearts!'],
  ['What do you call a fish that needs two eyes checked?', 'A see-bass!'],

  // --- Food riddles ---------------------------------------------------------
  ['What has a heart but no other organs?', 'A head of lettuce!'],
  ['What kind of nut is always cold?', 'A cashew, achoo!'],
  ['What do you call cheese that is not yours?', 'Nacho cheese!'],
  ['Why did the banana go to the doctor?', 'Because it was not peeling well!'],
  ['What do you get when you cross a snowman and a puppy?', 'Frostbite, but the friendly kind!'],
  ['What kind of key opens a banana?', 'A mon-key!'],
  ['Why did the cookie go to the nurse?', 'Because it felt crummy!'],
  ['What do you call an apple that plays trumpet?', 'A tooty fruity!'],
  ['What did the grape say when it got stepped on?', 'Nothing, it just let out a little wine!'],
  ['What do you call a sad strawberry?', 'A blueberry!'],
  ['Why did the orange stop rolling down the hill?', 'It ran out of juice!'],
  ['What is a pretzel\'s favorite dance?', 'The twist!'],
  ['What did one plate say to the other plate?', 'Dinner is on me!'],
  ['Why did the pancake cry?', 'It was on a roll and felt a little flat!'],
  ['What do you call two banana peels?', 'A pair of slippers!'],
  ['Why do bananas wear sunscreen?', 'So they don\'t peel!'],
  ['What kind of vegetable knits sweaters?', 'A cardi-gan, I mean a cardigan of course, made of yarn — but a cabbage works too!'],
  ['What did the little corn say to the mama corn?', 'Where is popcorn?'],
  ['Why did the muffin go to school?', 'To become a little smarter!'],

  // --- School riddles ---------------------------------------------------------
  ['Why did the pencil go to the dentist?', 'To get a new point!'],
  ['Why was the math book sad?', 'It had too many problems!'],
  ['Why did the student eat his homework?', "Because the teacher said it was a piece of cake!"],
  ['What is a teacher\'s favorite country?', 'Germany, because everyone always says "Class dismissed, guten tag!"'],
  ['Why did the boy bring a ladder to school?', 'Because he wanted to go to high school!'],
  ['What did the calculator say to the pencil?', "You can count on me!"],
  ['Why was the broom late to school?', 'It swept in!'],
  ['What is a computer\'s favorite snack?', 'Microchips!'],
  ['Why did the teacher wear sunglasses?', 'Because her students were so bright!'],
  ['What did the paper say to the pencil?', 'Write on!'],
  ['Why did the crayon go to school?', 'To draw a better future!'],
  ['What subject do fish like best in school?', 'Ocean-ography!'],
  ['Why did the backpack go to the doctor?', 'It was feeling zipped up inside!'],
  ['What is a book\'s favorite dessert?', 'A shelf-ish cake, hard to spell but easy to eat!'],
  ['Why did the ruler get in trouble?', 'It kept crossing the line!'],

  // --- Space riddles ------------------------------------------------------------
  ['Why did the sun go to school?', 'To get a little brighter!'],
  ['How do you organize a party in space?', 'You planet!'],
  ['Why is the moon so bad at eating?', 'Because it is always full!'],
  ['What did the astronaut say to the alien?', 'Nice to meteor!'],
  ['Why did the star break up with the planet?', 'Because it needed more space!'],
  ['What do you call an alien with three eyes?', 'An aliiien!'],
  ['Why did the rocket break up with the moon?', 'It needed some space!'],
  ['How does the solar system hold up its pants?', 'With an asteroid belt!'],
  ['What kind of music do planets sing?', 'Nep-tunes!'],
  ['What do you call a spaceship that lands on the beach?', 'A sand-dune buggy from outer space!'],
  ['Why did the astronaut break up with his girlfriend?', 'He needed some space!'],
  ['What did Saturn say to the other planets?', 'I have got you all encircled!'],
  ['Why is space so quiet?', 'Because there is no sound in a vacuum!'],
  ['What is an astronaut\'s favorite part of a computer?', 'The space bar!'],

  // --- Weather & nature riddles ------------------------------------------------
  ['What do you call a snowman in July?', 'A puddle!'],
  ['What did one raindrop say to the other?', "Two's company, three's a cloud!"],
  ['Why did the cloud go to school?', 'To get a little brighter!'],
  ['What did the tree say to autumn?', 'Leaf me alone!'],
  ['What do you call a very small valley?', 'A mini-valley, of course!'],
  ['Why did the leaf go to the doctor?', 'It was feeling a little green!'],
  ['What do trees drink?', 'Root beer!'],
  ['Why did the sun not go to college?', 'Because it already had a million degrees!'],
  ['What kind of tree fits into your hand?', 'A palm tree!'],
  ['Why is it hard to talk to a garden?', 'Because the corn has ears and the potatoes have eyes!'],
  ['What do you call a bear caught in the rain?', 'A drizzly bear!'],
  ['What did the ocean say to the beach?', 'Nothing, it just waved!'],

  // --- Dinosaur / pirate / robot riddles -----------------------------------------
  ['What do you call a dinosaur that is also a spy?', 'A spy-osaurus!'],
  ['What do you call a dinosaur that stays up all night reading?', 'A dino-snore, once it finally falls asleep!'],
  ['What do you call a dinosaur that loves to build sandcastles?', 'A sand-osaurus!'],
  ["Why don't dinosaurs talk anymore?", "Because they've been quiet for millions and millions of years!"],
  ['What is a pirate\'s favorite letter?', 'You would think it be R, but their first love is the C!'],
  ['Why couldn\'t the pirate find his treasure?', 'Because he was sitting on the deck!'],
  ['What do you call a pirate who skips class?', 'Captain Hooky!'],
  ['Why did the pirate go to the fair?', 'To ride the Ferris Wheel of Fortune!'],
  ['How much did the pirate pay for his hook and peg leg?', 'An arm and a leg!'],
  ['What do you call a robot who takes the long way around?', 'A rambling robot — it just loves to wander!'],
  ['Why was the robot so tired?', 'It had a hard drive!'],
  ['What do robots eat for a snack?', 'Computer chips!'],
  ['Why did the robot go on a diet?', 'It had a byte too many bytes!'],
  ['What did the robot say to the toaster?', 'You complete me!'],
  ['Why don\'t robots ever panic?', 'They have great nerves of steel!'],

  // --- Number & shape riddles -----------------------------------------------------
  ['Why was six afraid of seven?', 'Because seven eight nine!'],
  ['What did zero say to eight?', 'Nice belt!'],
  ['Why is the number ten so scary?', 'Because seven eight nine, and then it was ten!'],
  ['What shape is usually waiting for you?', 'A waiting rhombus... just kidding, a line!'],
  ['Why did the two fours skip lunch?', 'Because they already eight!'],
  ['What do you call a number that cannot keep still?', 'A roamin\' numeral!'],
  ['Why is the math book always sad?', 'Because it has so many problems!'],
  ['What did the triangle say to the circle?', "You're pointless!"],

  // --- Miscellaneous silly riddles ---------------------------------------------
  ['What kind of shoes do frogs wear?', 'Open-toad sandals!'],
  ['What do you call a boomerang that will not come back?', 'A stick!'],
  ['Why doesn\'t a robot ever ask for a balloon?', 'Because it would rather have a fresh set of batteries!'],
  ['What did one wall say to the other wall?', "I'll meet you at the corner!"],
  ['Why did the picture go to jail?', 'Because it was framed!'],
  ['What do you call a hot dog wrapped up in a warm blanket?', 'A snug dog!'],
  ['What did the janitor say when he jumped out of the closet?', 'Supplies!'],
  ['What do you call a fly without wings?', 'A walk!'],
  ['Why did the golfer bring two pairs of pants?', 'In case he got a hole in one!'],
  ['What did the ocean say to the sand?', 'Nothing, it just waved!'],
  ['Why did the scarecrow win an award?', 'Because he was outstanding in his field!'],
  ['What do you call cheese that isn\'t yours?', 'Nacho cheese!'],
  ['Why did the stadium get hot after the game?', 'All the fans left!'],
  ['What did the volcano say to the mountain?', 'I lava you!'],
  ['What kind of tree can you carry in your hand?', 'A palm!'],
  ['What did the buffalo say to his son when he left for school?', 'Bison!'],
  ['Why did the golfer bring an extra pair of socks?', 'In case he got a hole in one!'],
  ["What is a balloon's least favorite music?", 'Pop music!'],

  // --- Ocean riddles ---------------------------------------------------------
  ['What do you call a fish that wears a crown?', 'A king fish!'],
  ["Why don't crabs ever share their toys?", 'Because they are shellfish!'],
  ["What is a shark's favorite game at the pool party?", 'Swallow the leader!'],
  ['Why are fish so good at school?', 'Because they always swim in schools!'],
  ["What is a dolphin's favorite game show?", 'Whale of Fortune!'],
  ['What do you call a fish with two knees?', 'A tuna, if you squint!'],
  ['Why did the starfish turn a little pink?', 'Because the seaweed!'],
  ['What do you call an octopus who tells great jokes?', 'A comedi-tentacle!'],
  ['How does the ocean say hello every morning?', 'It waves!'],
  ['Why do oysters never share their pearls?', 'Because they are shellfish!'],
  ['What do pirates like to eat for dinner?', 'Fish and ships!'],
  ['What do you call a very polite shark?', 'A gentle-fin!'],
  ['Why did the fish blush at the seaweed?', 'Because the sea weed!'],
  ['What is a whale\'s favorite thing to do at recess?', 'Blow bubbles!'],
  ['What kind of fish only swims at night?', 'A starfish!'],
  ['Why did the crab never share its snacks?', 'Because it was a little shellfish!'],
  ['What do you call a seagull that lives near the bay?', 'A bay-gull!'],
  ['What did the little wave say to the big wave?', 'Nothing, waves cannot talk, but they sure can wave!'],
  ['What is an eel\'s favorite subject in school?', 'Current events!'],
  ['Why did the lobster stay red all summer?', 'Because it forgot its sunscreen!'],

  // --- Jobs & careers riddles -----------------------------------------------
  ['Why did the baker never have any money?', 'Because he always kneaded the dough!'],
  ['What did the firefighter name her two pet dogs?', 'Hose-A and Hose-B!'],
  ['What do you call a doctor who only fixes computers?', 'A screen-ologist!'],
  ['What does a baker use to measure ingredients?', 'A yeast-imate!'],
  ['What did the teacher say to the broken pencil?', "You're pointless, let's get you sharpened!"],
  ['Why did the astronaut decide to become a farmer?', 'Because he loved planting his flag in new ground!'],
  ['What do you call a chef who tells the best jokes?', 'A comedi-chef!'],
  ['What did the dentist say to the shy tooth?', "Don't worry, this won't hurt a bit!"],
  ['Why did the painter get invited to every party?', 'Because he always brought the colors!'],
  ['Why did the plumber get a big promotion?', 'Because he really knew how to go with the flow!'],
  ['What did the tailor say when business was slow?', "I guess I'll just have to sew some new customers!"],
  ['Why do librarians make the best detectives?', 'Because they always know how to find the right story!'],
  ['What does a farmer use to count his cows?', 'A cow-culator!'],
  ['Why did the artist feel so cool?', 'Because he was always drawing a crowd!'],
  ['What do you call a very tidy carpenter?', 'A board with a plan!'],

  // --- Vehicles & transportation riddles --------------------------------------
  ['Why did the bicycle fall asleep?', 'Because it was tired of pedaling all day!'],
  ['Why did the car get a flat tire?', 'Because there was a fork in the road!'],
  ["What do you call a truck that's always on time?", 'A punctu-al vehicle!'],
  ['What did the traffic light say to the car?', "Don't look, I'm changing!"],
  ['Why did the train have a cold?', 'It caught a little choo, I mean flu!'],
  ['What do you call a boat that never, ever sinks?', 'Unsinkable, of course!'],
  ['Why do bicycles fall over so easily?', 'Because they are two tired!'],
  ['What kind of vehicle does a very tidy person drive?', 'A clean machine!'],
  ['Why did the little red wagon need a rest?', 'Because it had been pulled all day!'],
  ['What did the tire say to the flat tire?', "What's up? You look deflated!"],
  ['Why did the scooter go to school?', 'To get a little more wheel-y smart!'],
  ['What do you call a car that loves to sing?', 'A car-aoke machine!'],

  // --- Toys & games riddles ----------------------------------------------------
  ['Why did the puzzle piece feel a little lost?', "Because it couldn't find where it fit in!"],
  ['What is a robot\'s favorite playground game?', 'Rock, paper, scissors, beep!'],
  ['Why did the yo-yo get invited to every party?', 'Because it always came right back!'],
  ["What is a teddy bear's favorite kind of pasta?", 'Fusilli, so it can give its plate a big hug!'],
  ['Why did the balloon skip the picnic?', "It didn't want to end up popping in!"],
  ['What do you call a kite that tells jokes?', 'A funny flyer!'],
  ['Why did the top hat get to be the leader?', "Because it was always ahead of everyone else!"],
  ['What game do baby dinosaurs love to play?', 'Roar and seek!'],
  ['Why did the drum go to the doctor?', 'It was feeling a little beat!'],
  ['What is a jigsaw puzzle\'s favorite phrase?', 'It will all come together in the end!'],

  // --- Colors riddles ------------------------------------------------------------
  ['Why did the crayon feel a little lonely?', 'Because it was blue!'],
  ["What is a robot's favorite color?", 'Metal-ic!'],
  ['What did the green light say to the red light?', "Don't look at me, I'm changing right now!"],
  ['Why did the artist paint everything green one week?', 'Because he was going through his grass period!'],
  ['What color is the wind on a very windy day?', 'Blew!'],
  ['What do you call a bear with no color at all?', 'A bare bear!'],
  ['Why did the orange crayon get picked first for the team?', 'Because it was always so a-peeling!'],
  ['What did the rainbow say after the storm?', "Look on the bright side, I'm finally here!"],

  // --- Insects & small creatures riddles ---------------------------------------
  ['Why did the bee go to the barber?', 'Because it had a buzz cut!'],
  ["What is a caterpillar's favorite kind of dance?", 'The wiggle!'],
  ['Why did the firefly get such good grades?', 'Because it was always so bright!'],
  ['What do you call an ant who skips school?', 'A truant-ant!'],
  ['Why did the spider learn how to code?', 'To build a better website!'],
  ['What is a ladybug\'s favorite number?', 'Six, one for each little leg!'],
  ['Why did the butterfly fail the test?', "Because it kept changing its answers, just like it changes shape!"],
  ['What do you call a very organized beehive?', 'A honeycomb full of order!'],

  // --- Body, senses & everyday objects riddles ---------------------------------
  ['What breaks the moment you say its name?', 'Silence!'],
  ['What kind of room has no doors or windows at all?', 'A mushroom!'],
  ['What can you catch, but never actually see coming?', 'A cold!'],
  ['What goes up and down but never actually moves?', 'A staircase!'],
  ['What has one eye but cannot see a single thing?', 'A needle!'],
  ['What kind of shoes do all spies wear?', 'Sneak-ers!'],
  ['What has a head, a foot, but no arms or legs?', 'A bed!'],
  ['What can go up a chimney down, but not down a chimney up?', 'An umbrella!'],
  ['What kind of table has no legs at all?', 'A timetable!'],
  ['What has one head, one foot, and four legs?', 'A bed!'],

  // --- Family & home riddles ----------------------------------------------------
  ['Why did the little cookie go visit the doctor?', 'Because it was feeling crummy!'],
  ['What did the grandpa clock say to the grandchild clock?', "Tick tock, time flies when you're having fun!"],
  ['Why did the family bring a ladder to the picnic?', "Because they heard the food was on a higher level!"],
  ['What do you call a very musical family?', 'A band of relatives!'],
  ['Why did the little broom get in trouble at home?', 'Because it kept sweeping things under the rug!'],
  ['What did the sleepy pillow say at bedtime?', 'I could really use a good rest!'],
  ['Why do families love camping so much?', "Because it's in-tents!"],
  ['What do you call a home built entirely out of jokes?', 'A pun-house!'],

  // --- Farm riddles -----------------------------------------------------------------
  ['Why did the scarecrow bring an extra hat to the field?', 'Just in case the wind blew the first one clean away!'],
  ['What do you call a sleepy farm animal?', 'A little horse... I mean hoarse!'],
  ['Why did the farmer plant a light bulb?', 'He wanted to grow a power plant!'],
  ['What kind of vegetable knows a lot of secrets?', 'A cabbage that keeps things under wraps!'],
  ['Why did the chicken join a band?', 'Because it already had the drumsticks!'],
  ['What do you call a cow that just had a baby?', 'De-calf-inated!'],
  ['Why do farmers make such great comedians?', 'Because they always know how to plow through a joke!'],
  ['What do you call a pig that takes the best selfies?', 'A ham!'],

  // --- Music & sports riddles --------------------------------------------------
  ['Why did the music teacher need a ladder?', 'To reach the high notes!'],
  ['What is a drum\'s favorite word?', 'Beat it!'],
  ['Why did the soccer ball skip the game?', 'It was feeling a little burned out and deflated!'],
  ["What is a basketball's favorite kind of joke?", 'One that really bounces back!'],
  ['Why did the piano get locked out of the house?', "Because it lost all its keys!"],
  ['What do you call a very musical dinosaur?', 'A tune-a-saurus!'],
  ['Why did the runner bring string to the race?', 'To tie for first place!'],
  ['What do you call a swimming competition between snails?', 'A very, very slow one!'],

  // --- More number, time & shape riddles ------------------------------------------
  ['What did the clock do when it was hungry?', 'It went back four seconds!'],
  ['Why did the number eight never fight the number nine?', 'Because seven eight nine and everyone learned their lesson!'],
  ['What shape are you supposed to wait patiently in?', 'A line!'],
  ['Why is a calendar always so popular?', 'Because it always has a lot of dates!'],
  ['What did the little triangle say when it grew up?', "I want to be well-rounded, just like a circle!"],
  ['What time is it when an elephant sits on your clock?', 'Time to get a new clock!'],
  ['Why did the clock get sent to time-out?', 'Because it kept tocking back!'],
  ['What is the favorite shape of a very sleepy mathematician?', 'A rest-angle!'],

  // --- More animal riddles -----------------------------------------------------
  ['What do you call a very tidy hippo?', 'A hippo-clean-us!'],
  ['Why do giraffes have such long necks?', "Because their feet smell and their heads are so far away!"],
  ['What do you call a camel with no humps?', 'Humphrey!'],
  ['Why did the chicken go to the seance?', 'To get to the other side!'],
  ['What do you call a rabbit that tells the best jokes?', 'A funny bunny!'],
  ['Why do bears have fur coats?', 'Because they would look silly in a raincoat!'],
  ['What do you call a very happy kangaroo?', 'A jolly hopper!'],
  ['Why did the elephant paint its toenails red?', 'So it could hide in the strawberry patch!'],
  ['What do you call an owl who loves math?', 'A wise old counter!'],
  ['Why did the little skunk get sent to its room?', 'For making a big stink about everything!'],
  ['What do you call a bear caught in a rainstorm without a coat?', 'A drizzly bear!'],
  ['Why did the puppy sit in the shade?', "Because it didn't want to be a hot dog!"],
  ['What do you call two spiders who just got married?', 'Newlywebs!'],
  ['Why did the flamingo stand on one leg?', "Because if it lifted the other one too, it would fall over!"],

  // --- Camping, seasons & holidays riddles --------------------------------------
  ['Why did the camper bring a ladder to the tent?', 'Because he wanted to reach new heights of comfort!'],
  ['Why do campfires make the best storytellers?', 'Because they are always so fired up!'],
  ['What do you call a snowman with a six-pack?', 'An abdominal snowman!'],
  ['Why did the snowman go looking through the carrot patch?', 'Because he was picking his nose!'],
  ['What do you get when you cross a snowman and a shark?', 'Frostbite!'],
  ['Why does a birthday cake always feel so cool?', 'Because it always gets iced!'],
  ['What did one candle say to the other candle on the cake?', "Are we going out tonight?"],
  ['Why is a calendar always exhausted in December?', "Because its year is almost up!"],
  ['What do you call a very cheerful snowflake?', 'A flurry of fun!'],
  ['Why did the leaf go see a doctor in October?', 'Because it was feeling a little green around the edges!'],
  ['What do you call a beach ball on vacation?', 'A little inflated with excitement!'],
  ['Why do sunflowers make terrible secret keepers?', 'Because they always turn to face the light!'],

  // --- Weather riddles, round two --------------------------------------------------
  ['What kind of bow can never be tied?', 'A rainbow!'],
  ['Why did the cloud get an award at school?', 'Because it was outstanding in its field of thunder!'],
  ['What did the thunder say to the lightning?', "You're shocking, but I'm the one who gets the credit!"],
  ['Why do hurricanes travel so fast?', "Because if they walked, they would be called slow-icanes!"],
  ['What is a tornado\'s favorite game?', 'Twister, of course!'],
  ['Why did the fog go to school?', 'To improve its outlook!'],
  ['What kind of weather do mice hate the most?', 'When it is raining cats and dogs!'],
  ['Why does rain never get invited to the party?', 'Because it always dampens the mood!'],

  // --- More school riddles ----------------------------------------------------------
  ['Why did the notebook look so sad?', 'Because it had too many things to write about!'],
  ['What did the pencil case say to the pencil?', "You've got a lot of points, keep them sharp!"],
  ['Why did the student bring a pillow to school?', 'Because it was a class about dreams!'],
  ['What is a librarian\'s favorite kind of fish?', 'A bookworm, if that even counts as a fish!'],
  ['Why did the school bus driver never lose a race?', 'Because he always knew a shortcut!'],
  ['What did the report card say to the parent?', "Nothing much has changed, I'm still your kid!"],
  ['Why did the crayon box feel so proud?', 'Because it was full of bright ideas!'],
  ['What is a math teacher\'s favorite kind of tree?', 'Geome-tree!'],
  ['Why did the whiteboard feel like a superstar?', 'Because it was always the center of attention!'],
  ['What did the student say about the tricky spelling test?', 'It was un-be-lieve-able!'],

  // --- More space riddles ------------------------------------------------------------
  ['Why did the astronaut bring a map into orbit?', "So he wouldn't get lost among the stars!"],
  ['What do planets like to read before bed?', 'Comet books!'],
  ['Why did the sun go to the doctor?', 'Because it was having a hot flash!'],
  ['What kind of songs do the planets sing together?', 'Nep-tunes!'],
  ['Why is it so easy to make plans in space?', "Because you always have plenty of planet!"],
  ['What do you call a planet that loves to read?', 'A well-read planet, full of stars in its eyes!'],
  ['Why did the astronaut take a ladder into space?', 'To reach for the stars!'],
  ['What is an astronaut\'s favorite key on the keyboard?', 'The space bar, obviously!'],

  // --- Dinosaur, pirate & robot riddles, round two -----------------------------------
  ['Why did the dinosaur cross the playground?', "Because the see-saw hadn't been invented yet!"],
  ['What do you call a dinosaur that loves to nap?', 'A dino-snore!'],
  ['Why do dinosaurs make terrible library patrons?', 'Because they always leave giant footprints!'],
  ['What do you call a pirate with two eyes and two legs?', 'A rookie, he hasn\'t earned his patch yet!'],
  ['Why did the pirate captain buy an eye patch?', 'To keep his other eye a secret!'],
  ['What do you call a robot that loves to garden?', 'A ro-bot-anist!'],
  ['Why did the robot cross the playground?', 'To get to the other slide, one byte at a time!'],
  ['What does a robot say when it finishes a race?', "Beep beep, I'm charged up and ready to celebrate!"],

  // --- More number & logic riddles -------------------------------------------------
  ['What do you call a number that can never sit still?', 'A roaming numeral!'],
  ['Why is the number six always so calm?', 'Because seven, eight, nine never bothered it after all!'],
  ['What is a math teacher\'s favorite season?', 'Sum-mer!'],
  ['Why did the fraction feel left out?', 'Because it never felt like a whole number!'],
  ['What did zero say to the number eight?', 'Nice belt!'],
  ['Why do mathematicians love nature so much?', 'Because it has so many natural numbers!'],
  ['What shape is always waiting patiently in line?', 'A rect-angle, standing up nice and straight!'],
  ['Why did the two half-pizzas get along so well?', 'Because together they made a whole!'],

  // --- More food riddles ---------------------------------------------------------------
  ['Why did the strawberry cross the road?', 'To get to the jam session!'],
  ['What do you call cheese that is sad?', 'Blue cheese!'],
  ['Why did the egg hide?', 'Because it didn\'t want to be spotted!'],
  ['What kind of bread does a squirrel like best?', 'Nutty bread!'],
  ['Why did the sandwich go to the gym?', 'To get a little more bread and butter, I mean muscle!'],
  ['What do you call a very cool cucumber?', 'A cool as a cucumber, naturally!'],
  ['Why did the biscuit cry?', "Because its mom was a wafer so long!"],
  ['What did the little teapot say when it grew up?', "I'm feeling a little steamed today!"],
  ['Why do peppers make everyone laugh?', "Because they're a little spicy with their jokes!"],
  ['What kind of soup do robots love the most?', 'A can of oil-y noodle soup!'],

  // --- Everyday object riddles, round two -----------------------------------------------
  ['What can run but never actually walks?', 'A faucet!'],
  ['What has a face and two hands but no arms or legs?', 'A clock!'],
  ['What kind of coat is always wet when you put it on?', 'A coat of paint!'],
  ['What has many keys but cannot open a single door?', 'A keyboard!'],
  ['What can you fill with empty hands?', 'Gloves!'],
  ['What goes up but never actually comes back down again?', 'Your age, every single year!'],
  ['What kind of band never plays any music?', 'A rubber band!'],
  ['What has one head, four legs, and only wags at the end?', 'A dog!'],
];

// ---------------------------------------------------------------------------
// ONE-LINERS — plain punchline strings.
// ---------------------------------------------------------------------------
const ONELINER_BANK = [
  // --- Classic "why did the X cross the road" -------------------------------
  'Why did the chicken cross the road? To get to the other side!',
  'Why did the turtle cross the road? To get to the shell station!',
  'Why did the cow cross the road? To get to the moo-vie theater!',
  'Why did the bee cross the road? To get to the buzz stop!',
  'Why did the kangaroo cross the road? To get to the bounce house!',
  'Why did the fish cross the ocean? To get to the other reef!',
  'Why did the dinosaur cross the road? Because chickens hadn\'t evolved yet!',
  'Why did the robot cross the road? To get to the other site — the website!',
  'Why did the pirate cross the road? To get to the second-hand shop!',
  'Why did the frog cross the road? To get to the croak-room!',
  'Why did the duck cross the playground? To get to the other slide!',
  'Why did the spider cross the computer? To check out the website!',
  'Why did the scarecrow cross the road? He had straw everywhere and needed a change of scenery!',
  'Why did the snail cross the road? To get to the shell station, very, very slowly!',
  'Why did the owl cross the road? To prove he wasn\'t a chicken!',

  // --- "Why did the X do Y? Because Z" --------------------------------------
  'Why did the bicycle fall over? Because it was two tired!',
  'Why did the golfer wear two pairs of pants? Because he was afraid of getting a hole in one!',
  'Why did the cookie go to the doctor? Because it was feeling crummy!',
  'Why did the banana go to the party alone? Because it had no-body to go with!',
  'Why did the math book look so sad? Because it had too many problems!',
  'Why did the computer go to the doctor? Because it had a virus!',
  'Why did the tomato turn red? Because it saw the salad dressing!',
  'The scarecrow waved to every single bird in the field, hoping to make a new friend!',
  'Why did the teddy bear say no to dessert? Because it was already stuffed!',
  'Why did the sun refuse to go to college? Because it already had a million degrees!',
  'Why did the broom get a promotion? Because it was outstanding at sweeping the competition!',
  'Why did the calendar feel popular? Because it had a lot of dates!',
  'Why did the pillow go to the doctor? Because it was feeling a little flat!',
  'Why did the balloon pop out of nowhere? Because it just needed to let off some steam!',
  'Why did the clock get sent to the principal\'s office? For tocking too much!',
  'Why did the umbrella get promoted? Because it was outstanding in every kind of weather!',
  'Why did the crayon stay home from school? It wasn\'t feeling very colorful!',
  'Why did the light bulb fail the test? Because it wasn\'t very bright that day!',
  'Why did the kite refuse to fly? It was afraid of a little competition — the wind!',
  'Why did the toothbrush look so sad? Because everyone kept talking behind its back!',
  'Why did the stairs get in trouble? Because they were always up to something!',
  'Why did the string wear a hat? Just to be a little frayed of the cold!',
  'Why did the door lock go to school? To get a little brighter about security!',
  'Why did the pancake give up? It just felt too flat that day!',
  'Why did the shoe stay home from the race? It had cold feet!',
  'Why did the calendar apologize? For being a little date-d!',
  'Why did the paintbrush get invited to every party? Because it always brought color!',
  'Why did the ice cream truck break down? It had a rocky road!',
  'Why did the volcano skip lunch? It was already full of hot lava!',
  'Why did the noodle jump up and down before dinner? Because it was pasta-tively excited!',
  'Why did the pillow join the choir? Because it always had great feathers!',
  'Why did the sock go on a hike? To find its missing partner!',
  'Why did the fan get an award? Because it was always cool under pressure!',
  'Why did the cloud get grounded? For being a little too thunderous at dinner!',
  'Why did the snowman look so happy? Because the sun finally came out to play!',
  'Why did the bee get married? Because he found his honey!',
  'Why did the octopus win the art contest? Because it was well armed with talent!',
  'Why did the vacuum cleaner join the band? Because it really knew how to suck up a beat!',
  'Why did the garden grow so fast? Because the sunflowers led the way!',
  'Why did the mushroom get invited to every party? Because he was such a fungi!',

  // --- Pun statements ------------------------------------------------------
  'I used to be a baker, but I couldn\'t make enough dough!',
  'I would tell you a chemistry joke, but I know I wouldn\'t get a reaction!',
  'I only know 25 letters of the alphabet. I don\'t know Y!',
  'I tried to catch some fog earlier, but I mist!',
  'A snail without a shell is not lazy, just a little slug-gish!',
  'I stayed up all night wondering where the sun went, then it dawned on me!',
  'My favorite math teacher had a lot of problems, but she solved them all!',
  'I told a joke about a broken pencil, but it was pointless!',
  "I asked the librarian if the library had books about paranoia. She whispered, \"They're right behind you!\"",
  'The math teacher called in sick with algebra — she had too many problems!',
  'I ordered a chicken and an egg from a friend. I will let you know which comes first!',
  'A book never gets cold because it always has a jacket!',
  'I used to play piano by ear, but now I use my hands!',
  'The best time to go to the dentist is tooth-hurty!',
  'I made a belt out of watches once. It was a huge waist of time!',
  'I am reading a book about anti-gravity. It is impossible to put down!',
  'A perfectly balanced diet is a cookie in each hand!',
  'I would love to tell you a joke about pizza, but it is a little too cheesy!',
  'I told my suitcase we are not going on vacation, and now I have baggage!',
  'My new thesaurus is terrible. Not only that, it is also terrible!',
  'A boiled egg every morning is hard to beat!',
  'I tried to write a joke about a pencil, but it kept losing its point!',
  'The scariest music note is B-flat, because it has no natural friends!',
  'A single sock never likes parties, because it never has a partner to go with!',
  'I planted some birdseed once. A bird came up, so I do not know what to do with it!',
  'I stayed up all night to see where the sun went, and then it dawned on me!',
  'What do you call a factory that makes okay products? A satisfactory!',
  'I used to hate facial hair, but then it grew on me!',
  'A magician was walking down the street and then he turned into a store!',
  'I have a joke about paper, but it is tearable!',
  'I did not like my beard at first, then it grew on me!',
  'I wondered why the baseball kept getting bigger, then it hit me!',
  'A cheese shop in France ran completely out of everything except one kind: de Brie!',
  'I have a fear of speed bumps, but I am slowly getting over it!',
  'I could tell a joke about noses, but it might not be very scent-sible!',
  'The world tongue-twister champion practiced every single day, and it really paid off, sentence by sentence!',
  'A pun writer needs the write words to make everyone smile!',
  'I really want to tell a milk carton joke, but it might be a little too spoiled!',
  'The origami teacher told me his job was folding, so he retired early!',
  'A grape stepped on a banana. The banana just let out a little wine!',

  // --- Animal one-liners -----------------------------------------------------
  'Two goldfish are in a tank, and one turns to the other and says, "Do you even know how to drive this thing?"',
  'What do you call a fish with no eye? A fsh — every kid loves this one!',
  'A frog hopped into the bank to ask for a loan. The teller said, "No problem, we will just need your rib-bit card!"',
  'A cow says moo, a duck says quack, and a very sleepy owl just says "not right now, please!"',
  'The turtle told the snail, "Slow down, you are making me look bad!"',
  'The elephant packed his trunk and went on vacation!',
  'A herd of cows went to a concert. They said the band was un-be-lieve-udder-ble!',
  'A bear walked into the campsite and said, "This porridge is just right!"',
  'The dinosaur wore his favorite roar-some sweater to school!',
  'A penguin walked into the wrong meeting and said, "Sorry, I think I am in the wrong huddle!"',
  'The kangaroo forgot his keys, so he had to hop back home!',
  'The chameleon failed the color test, because it kept changing its answer!',
  'The owl stayed up all night studying, because it is a real night owl!',
  'The koala never rushes anywhere, because it likes to take things slow and steady!',
  'The rooster showed up late to school, so he had to crow about it later!',
  'The octopus learned to juggle really fast, because it has eight extra hands!',
  'The zebra could never decide what to wear, black stripes or white stripes!',
  'A family of tomatoes was walking down the street. The baby tomato kept falling behind, so the papa tomato said, "Ketchup!"',
  'The snail entered a race and everyone cheered, because it was still faster than a Monday morning!',
  'A giraffe never gets cold feet, because its feet are much too far away to notice!',

  // --- School one-liners --------------------------------------------------
  'My teacher told me to bring something interesting for show and tell. I brought myself!',
  'I finally understood fractions, and it was a whole new experience!',
  'The library book about clouds was a real page-turner!',
  'My homework said "please do the following," so I did the following: nothing!',
  'The math teacher used graph paper because she liked to plot things!',
  'I got a hundred percent on my spelling test, and it felt like an A-plus achievement!',
  'The pencil sharpener told the pencil, "You are looking sharp today!"',
  'My backpack was so heavy, I told it to carry itself for once!',
  'The classroom clock always makes second-hand jokes!',
  'The chalkboard was a real class act!',

  // --- Space one-liners -----------------------------------------------------
  'Space is huge, but somehow my little brother still finds a way to take up all of it!',
  'A rocket ship applied for a job, and it got hired on the spot!',
  'The astronaut brought a snack to space, just in case she got a little hungry between stars!',
  'The moon does not need to shout, because it is already the center of attention every night!',
  'A UFO landed in the backyard and asked to borrow a cup of sugar, then it flew off in a hurry!',
  'The planets held a big meeting, and Earth said it was just happy to be there!',
  'A comet zoomed by so fast, it barely had time to wave hello!',
  'The stars come out every night for one reason: to shine!',
  'An astronaut always packs light, because everything weighs less in space anyway!',
  'The solar system throws the best parties, because it always has plenty of space!',

  // --- Dinosaur / pirate / robot one-liners ---------------------------------
  'The triceratops never gives up, no matter how many horns it takes to finish the job!',
  'A dinosaur\'s favorite exercise is the dino-stretch, right before a nap!',
  'The pirate\'s favorite subject in school was arrrrt!',
  'The pirate ship never got lost, because it always had a great sense of arrrrection!',
  'A robot fell in love with a calculator, because it really added up!',
  'The robot loved to dance, because it had all the right moves programmed in!',
  'A dinosaur tried out for the choir, but it could only manage a really loud roar!',
  'The pirate captain always says please and thank you, because manners matter, even on the high seas!',
  'The robot went to sleep every night by simply powering down!',
  'A young dinosaur asked its mom why the sky was blue, and she said, "Ask your dad-asaurus!"',

  // --- Weather / nature one-liners -------------------------------------------
  'The cloud never worries about anything, it just goes with the flow!',
  'A raindrop asked another raindrop for directions, and they just went with the flow!',
  'The sunflower always looks on the bright side!',
  'A snowflake never repeats itself, because every single one is one of a kind!',
  'The wind loves telling stories, especially the ones that really blow you away!',
  'A rainbow showed up after the storm just to say hello!',
  'The tree stood tall all day, just branching out and making new friends!',
  'A puddle told the sun, "Please stick around, I am having the time of my life!"',
  'The garden threw a party, and every flower was invited to bloom!',
  'A snowman\'s favorite breakfast is snowflakes and hot cocoa!',

  // --- Misc silly one-liners -----------------------------------------------
  'My favorite color is invisible, because I can never quite find it!',
  'I told my dog a joke about a ball, and it just started chasing its tail!',
  'The clock in the kitchen is always running a little behind schedule!',
  'The ladder was afraid of heights, so it just decided to lie down for a while!',
  'The balloon felt a little light-headed after a big party!',
  'My alarm clock and I do not get along, we are always arguing about the time!',
  'The staircase always has its ups and downs!',
  'The calendar has 365 days, and every single one is a chance for a new joke!',
  'The mirror never lies, it just reflects the truth right back at you!',
  'The trampoline is always up for a good time!',
  'The candle burned all night, and by morning it was really wick-ed tired!',
  'The bubble wrap could not stop popping off with excitement!',
  'The blanket always keeps its cool, even during the coziest naps!',
  'The pillow fight ended in a real feather-brained mess!',
  'The birthday cake always has one more thing to say: many happy returns!',

  // --- Ocean one-liners ------------------------------------------------------
  'The crab never rushes anywhere, it just likes to sidestep the whole situation!',
  'The jellyfish is always so relaxed, it just goes with the flow!',
  'The lobster refused to share its snacks, because it was feeling a little shellfish!',
  'The octopus learned to play eight instruments at once, one for each arm!',
  'The dolphin told the funniest jokes, because it always had a splash of humor!',
  'The seahorse never rushes into anything, it just takes things nice and slow!',
  'The starfish always shines the brightest at the bottom of the sea!',
  'The whale never needs a microphone, it already has the biggest voice in the ocean!',
  'The clownfish told a joke so funny, the whole reef cracked up!',
  'The sea turtle takes its time with everything, and it always gets there in the end!',
  'The shark showed up to the pool party fashionably late, as always!',
  'The seagull loves a good snack, especially anything left unattended!',

  // --- Music one-liners ----------------------------------------------------
  'The piano never gets nervous, because it always knows how to play it cool!',
  'The drum set loves a good rhythm, especially first thing in the morning!',
  'The trumpet always toots its own horn, because someone has to!',
  'The violin section is always in tune with how everyone else is feeling!',
  'The tambourine loves to shake things up wherever it goes!',
  'The choir practiced so hard, they were absolutely note-worthy!',
  'The guitar string finally snapped from all the tension, but it bounced right back!',
  'The band practiced every day, because they really wanted to nail the big note!',
  'The harmonica always has something to say, one breath at a time!',
  'The xylophone never runs out of things to say, key by key!',

  // --- More animal one-liners -------------------------------------------------
  'The hedgehog is a little prickly in the morning, but it warms up fast!',
  'The sloth takes its time with everything, but it always finishes eventually!',
  'The peacock spent all morning getting ready, just to show off its colors!',
  'The camel never complains about the heat, it just takes it in stride!',
  'The chipmunk stuffed its cheeks so full, it could barely say good morning!',
  'The flamingo balances on one leg all day, just to keep things interesting!',
  'The panda spends most of the day eating bamboo and taking naps, which sounds like a great plan!',
  'The parrot repeats everything it hears, especially the good jokes!',
  'The raccoon washed its snack before eating it, because cleanliness matters!',
  'The porcupine gives the best hugs from a very safe distance!',
  'The armadillo curled up into a little ball, just to feel extra cozy!',
  'The platypus is proof that nature loves a good surprise!',
  'The chameleon changed colors so fast, nobody could keep up!',
  'The meerkat stood watch all day, taking its job very seriously!',
  'The walrus has the best mustache in the entire animal kingdom!',
  'The hummingbird moves so fast, it practically invented multitasking!',
  'The penguin waddled to the front of the line, because it was worth the wait!',
  'The baby goat jumped for joy all afternoon, for absolutely no reason at all!',
  'The turtle wins every staring contest, because it never blinks first!',
  'The bunny hopped straight past everyone, because it had somewhere important to be!',

  // --- School one-liners --------------------------------------------------
  'My spelling test had one tricky word, and I nailed it: R-E-C-E-S-S!',
  'The chalkboard always has something to say, one lesson at a time!',
  'The report card came home and said, "Room for improvement," so I made more room on my desk!',
  'The school bus arrives on time every single day, rain or shine!',
  'My locker combination is a total mystery, even to me most mornings!',
  'The class hamster is the real principal of this school, everyone agrees!',
  'The science fair volcano erupted right on schedule, baking soda and all!',
  'My favorite class is definitely lunch, closely followed by recess!',
  'The library was so quiet, you could practically hear the pages turn!',
  'The whiteboard marker ran out of ink right in the middle of the big lesson!',

  // --- Space one-liners ------------------------------------------------------
  'The astronaut always double-checks the checklist, because space has zero room for mistakes!',
  'The rocket ship counted down from ten, just to build a little suspense!',
  'The moon changes its shape every single night, just to keep things interesting!',
  'The stars come out every evening for one job only: to shine as bright as possible!',
  'The telescope spends every clear night looking for new friends among the stars!',
  'The astronaut packed extra snacks, because space walks make you hungry!',
  'The comet zoomed by so fast, it barely had time to say hello!',
  'The space station orbits the Earth sixteen times a day, which is a lot of laps!',

  // --- Dinosaur, pirate & robot one-liners ---------------------------------------
  'The triceratops never backs down from a challenge, horns and all!',
  'The pirate\'s parrot repeated every joke twice, just to be sure everyone laughed!',
  'The robot practiced its dance moves every night until it got them just right!',
  'The dinosaur always wins the staring contest, mostly because nobody wants to argue!',
  'The pirate captain never gets lost, because the map is always close at hand!',
  'The robot charges its batteries every night, ready for a brand new day!',
  'The stegosaurus never rushes, it just takes each step one plate at a time!',
  'The pirate ship sailed smoothly, guided by the brightest star in the sky!',

  // --- Sports one-liners --------------------------------------------------
  'The soccer ball rolled all the way home, because it just could not stop!',
  'The basketball always bounces back, no matter how hard the day gets!',
  'The runner crossed the finish line and immediately asked when the next race was!',
  'The swimmer practiced every morning, rain or shine, splash or no splash!',
  'The baseball team celebrated every single run, big or small!',
  'The gymnast landed the perfect cartwheel, right on the very first try!',
  'The bowling ball rolled straight for the pins and never looked back!',
  'The tennis match went into overtime, and everyone cheered until the very end!',

  // --- Vehicles one-liners --------------------------------------------------
  'The little red wagon pulled its weight all afternoon, without a single complaint!',
  'The school bus took the scenic route today, just to enjoy the sunshine!',
  'The bicycle bell rang the whole way down the street, just for fun!',
  'The train chugged along right on schedule, whistle blowing the whole way!',
  'The scooter zipped around the block twice before anyone even noticed!',
  'The airplane climbed above the clouds, just to get a better view!',
  'The rowboat drifted along the lake without a single worry in the world!',
  'The fire truck raced down the street, sirens blaring, ready to help!',

  // --- Toys & games one-liners -----------------------------------------------
  'The kite soared higher and higher, chasing the wind the whole afternoon!',
  'The board game lasted three hours, and everyone still wanted one more round!',
  'The teddy bear got the biggest hug of the entire day, no contest!',
  'The jigsaw puzzle finally came together, piece by piece, right before bedtime!',
  'The toy robot marched across the room, beeping the whole way!',
  'The bubble machine filled the whole yard with floating little rainbows!',
  'The building blocks turned into a castle by the time snack time rolled around!',
  'The marbles rolled clean across the floor and hid under the couch, as always!',

  // --- Weather & seasons one-liners -------------------------------------------
  'The snowflake floated down slowly, taking its own sweet time to land!',
  'The sunflower turned to follow the sun all day long, never missing a beat!',
  'The rainbow showed up right after the storm, just to say hello!',
  'The autumn leaves fell one by one, painting the yard in gold and orange!',
  'The summer breeze rolled through the yard, cool and easy the whole afternoon!',
  'The snowman stood proud all winter, carrot nose and all!',
  'The thunderstorm rumbled through, then cleared up just in time for a rainbow!',
  'The garden bloomed overnight, as if it had been saving up all its colors!',

  // --- Family & home one-liners ------------------------------------------------
  'The family game night lasted way past bedtime, and nobody minded one bit!',
  'The kitchen smelled like fresh cookies all afternoon, and everyone followed their nose!',
  'The living room turned into a blanket fort by dinnertime, no permission required!',
  'The family dog waited by the door every day, right on schedule!',
  'The grandparents told the same story twice, and it was still the best part of the day!',
  'The backyard barbecue brought the whole family together, plates and all!',
  'The bedtime story got one more chapter, because nobody wanted it to end!',
  'The family photo took twelve tries, because someone always blinked!',

  // --- Jobs one-liners ---------------------------------------------------------
  'The baker\'s kitchen smelled like fresh bread from sunrise to sunset!',
  'The firefighter checked every smoke alarm twice, just to be extra safe!',
  'The mail carrier waved to every single house on the street, without fail!',
  'The teacher gave out gold stars all week, one for every good idea!',
  'The doctor kept a jar of stickers ready for every brave patient!',
  'The farmer woke up before the rooster, every single morning!',
  'The chef flipped the pancake so high it nearly touched the ceiling!',
  'The librarian knew exactly where every single book belonged!',

  // --- More pun statements & silly one-liners -----------------------------------
  'The garden gnome stood guard all night, never once falling asleep on the job!',
  'The umbrella opened up right on cue, just as the first raindrop fell!',
  'The doormat welcomed everyone with a smile, rain or shine!',
  'The wind chime sang a little tune every time the breeze came through!',
  'The bookshelf held every story imaginable, all lined up and ready to go!',
  'The birthday balloon floated straight up to the ceiling and stayed there all party long!',
  'The picnic blanket spread out perfectly under the shade of the big oak tree!',
  'The treehouse became the best clubhouse in the whole neighborhood!',
  'The sandcastle stood tall until the very last wave came to say goodnight!',
  'The lemonade stand sold out in an hour, one cup at a time!',
  'The paper airplane flew clear across the room on its very first flight!',
  'The chalk drawing covered the entire driveway by the end of the afternoon!',
  'The wagon full of pumpkins rolled all the way down the hill on its own!',
  'The tree house had the best view in the whole backyard!',
  'The scavenger hunt lasted all afternoon, and every clue led to more giggles!',
  'The snow globe shook up a little blizzard every single time!',
  'The seesaw never stopped going up and down, all recess long!',
  'The merry-go-round spun so fast, everyone forgot which way was which!',
  'The sprinkler turned the whole backyard into the best water park around!',
  'The campfire told the best stories, one crackle at a time!',

  // --- Insects & colors one-liners ---------------------------------------------
  'The firefly lit up the whole backyard, one little blink at a time!',
  'The ladybug landed on my hand and stayed for a whole story!',
  'The bee buzzed from flower to flower, never once losing track!',
  'The ant carried a crumb twice its size, without even breaking a sweat!',
  'The butterfly took its time deciding which flower to visit next!',
  'The dragonfly zipped across the pond so fast, it left a tiny rainbow behind!',
  'The crayon box argued about who got to color the sky, but blue won every time!',
  'The rainbow crayon always finished first, because it never had to choose just one color!',
  'The paintbrush danced across the page, leaving a trail of every color at once!',
  'The color wheel spun around and around, just showing off!',

  // --- More numbers & shapes one-liners -----------------------------------------
  'The number line stretched on forever, one step at a time!',
  'The calculator solved every problem before anyone even finished asking!',
  'The circle rolled happily down the hill, no corners to slow it down!',
  'The square always stood up straight, four corners and proud!',
  'The counting book never got old, because there was always one more number to learn!',
  'The abacus clicked along happily, bead by bead!',
  'The clock hands raced around all day, and the little hand always came in last!',
  'The calendar flipped to a brand new month, ready for a fresh start!',

  // --- More holiday & birthday one-liners -----------------------------------------
  'The birthday candles all got blown out in one big wish-filled breath!',
  'The party hat stayed on the whole afternoon, no matter how much dancing happened!',
  'The confetti rained down the moment the party really got started!',
  'The piñata held on tight until the very last swing!',
  'The gift wrap came off in one big triumphant tear!',
  'The birthday song got sung twice, because once was simply not enough!',
  'The party favors disappeared within the first five minutes, every single time!',
  'The cake had three layers, and every single one disappeared by dessert time!',

  // --- More food one-liners -----------------------------------------------------
  'The popcorn popped so fast, it practically made its own fireworks show!',
  'The ice cream truck song could be heard from three blocks away, every single time!',
  'The pizza slice disappeared before anyone even finished singing happy birthday!',
  'The lemonade stayed nice and cold, right up until the very last sip!',
  'The cookie jar mysteriously emptied itself by the end of every single day!',
  'The sandwich stayed perfectly stacked all the way to the very last bite!',
  'The smoothie blended up so smooth, not a single lump remained!',
  'The waffle had exactly enough syrup pockets for every single bite!',

  // --- More silly everyday one-liners -----------------------------------------------
  'The rubber duck floated proudly at the front of every single bath!',
  'The night light stayed on all night, keeping watch over the whole room!',
  'The pajamas were the comfiest thing in the entire house, no contest!',
  'The alarm clock rang right on time, whether anyone wanted it to or not!',
  'The toothbrush danced around every tooth, twice a day, without fail!',
  'The backpack carried everything important, right down to the very last snack!',
  'The bookmark saved the exact spot, no matter how many times the book closed!',
  'The flashlight lit up the whole blanket fort in an instant!',
  'The rain boots splashed through every single puddle on the way to school!',
  'The winter mittens kept every finger warm, one snowball fight at a time!',
];

// ---------------------------------------------------------------------------
// Assemble the flat export. IDs are zero-padded and assigned purely by
// position within each literal bank above — append new entries at the end
// of a bank rather than inserting in the middle, so existing ids stay put.
// ---------------------------------------------------------------------------
const knockKnockJokes = KNOCK_KNOCK_BANK.map(([name, punchline], i) => ({
  id: `kk-${String(i + 1).padStart(4, '0')}`,
  type: 'knock-knock',
  name,
  punchline,
}));

const riddleJokes = RIDDLE_BANK.map(([question, answer], i) => ({
  id: `riddle-${String(i + 1).padStart(4, '0')}`,
  type: 'riddle',
  question,
  answer,
}));

const onelinerJokes = ONELINER_BANK.map((text, i) => ({
  id: `oneliner-${String(i + 1).padStart(4, '0')}`,
  type: 'oneliner',
  text,
}));

export const JOKES = [...knockKnockJokes, ...riddleJokes, ...onelinerJokes];
export const JOKE_COUNT = JOKES.length;
